apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - namespace.yaml

helmCharts:
  - name: flux2
    repo: https://fluxcd-community.github.io/helm-charts/
    releaseName: flux2
    version: 2.14.0
    namespace: flux-system
    valuesInline:
      notificationController:
        create: false
      kustomizeController:
        create: false
      imageReflectionController:
        create: false
      imageAutomationController:
        create: false
      helmController:
        create: false
