apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

patches:
  - patch: |-
      - op: add
        path: /metadata/annotations/argocd.argoproj.io~1sync-options
        value: ServerSideApply=true
    target:
      kind: CustomResourceDefinition
      name: terraforms.infra.contrib.fluxcd.io

helmCharts:
  - name: tf-controller
    repo: https://flux-iac.github.io/tofu-controller/
    releaseName: tf-controller
    version: v0.16.0-rc.4
    namespace: flux-system
    includeCRDs: true
    valuesInline:
      allowCrossNamespaceRefs: false
      metrics:
        enabled: true
      imagePullSecrets:
        - name: ghcr-token
      runner:
        image:
          repository: ghcr.io/liatrio/pop-platform-library
          tag: tf-runner-8d2acfe
