apiVersion: v1
kind: ServiceAccount
metadata:
  name: awssm
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: awssm-pop-platform-secretstore
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: awssm
            namespace: external-secrets
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ghcr-token
  namespace: external-secrets
spec:
  secretStoreRef:
    name: awssm-pop-platform-secretstore
    kind: ClusterSecretStore
  refreshInterval: "5m"
  target:
    name: ghcr-token
    template:
      type: kubernetes.io/dockerconfigjson
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: pop-platform_global_ghcr_token
