---
apiVersion: generators.external-secrets.io/v1alpha1
kind: GithubAccessToken
metadata:
  name: github-auth-token
spec:
  appID: "1040678"
  installID: "56550736"
  url: "https://api.github.com"
  auth:
    privateKey:
      secretRef:
        name: github-app-pem
        key: githubAppPrivateKey
---
apiVersion: v1
kind: Secret
metadata:
  name: github-app-pem
  namespace: external-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: "argocd/argocd-repo-creds-github-app"
type: Opaque
stringData:
  key: cGxhY2Vob2xkZXIK
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: github-auth-token
spec:
  refreshInterval: "5m"
  target:
    name: github-auth-token # Name for the secret to be created on the cluster
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      data:
        username: tokenuser
        password: "{{ .token }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitconfig-with-token
spec:
  refreshInterval: "15m"
  target:
    name: gitconfig-with-token # Name for the secret to be created on the cluster
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      data:
        gitconfig: |
          [url "https://git:{{ .token }}@github.com/"]
          insteadOf = https://github.com/
          insteadOf = git://github.com:
          insteadOf = git@github.com:
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: argocd-repo-creds-github-app
spec:
  refreshInterval: "5m"
  target:
    name: argocd-repo-creds-github-app # Name for the secret to be created on the cluster
    template:
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflects-auto-enabled: "true"
          reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "argocd,flux-system"
          argocd.argoproj.io/secret-type: "repo-creds"
      data:
        username: tokenuser
        password: "{{ .token }}"
        url: https://github.com
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: GithubAccessToken
          name: github-auth-token
