apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: reloader

helmCharts:
  - name: reloader
    repo: https://stakater.github.io/stakater-charts
    version: 1.1.0
    releaseName: reloader
    namespace: reloader
    includeCRDs: true
    valuesInline:
      fullnameOverride: reloader

resources:
  - namespace.yaml
